# Generated by Django 6.0.1 on 2026-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Error'),
        ),
        migrations.AddField(
            model_name='task',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='Log'),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Worker PID'),
        ),
    ]
